import LocalizedString from 'react-native-localization';

const strings = new LocalizedString({
  en: {
    dob: 'birthday',
    emailAddress: 'email address',
    slideOneHeader: 'Stylish hair',
    slideOneDesc: 'Explore interesting and modern hairstyles from experts.',
    slideTwoHeader: 'Best deals',
    slideTwoDesc: 'Experience best hair deals in our different stores.',
    slideThreeHeader: 'Fast booking',
    slideThreeDesc:
      'With our new and efficient app, you can make fast bookings online.',
    firstName: 'first name',
    lastName: 'last name',
    confirmPassword: 'confirm password',
    login: 'Log in',
    phone: 'phone',
    password: 'password',
    signup: 'Sign up',
    createAccount: 'Create Account',
    forgotPassword: 'Forgot password?',
    rememberMe: 'Remember me',
    editProfile: 'Edit Profile',
    credits: 'Credits and Coupons',
    changeLanguage: 'Dili değiştir',
    settings: 'Settings',
    logOut: 'Log out',
    inviteFriends: 'Invite Friends',
    administrator: 'Administrator',
    alreadyAccount: 'Already have an account?',
    welcomeScreenText: 'Beautiful and exclusive styles.',
    getStarted: 'Get Started',
    tabExplore: 'Explore',
    tabServices: 'Services',
    tabDeals: 'Deals',
    tabBookings: 'Bookings',
    tabProfile: 'Profile',
    headerTodaysDeal: "Today's Deal",
    headerPopular: 'Popular',
    headerFavorites: 'Favorites',
    subHeaderPopular: 'Our most viewed services',
    viewAll: 'View all',
    subHeaderDeals: 'Special offer for today',
    bookNow: 'BOOK NOW',
    noBookingError: "You've not booked yet!",
    creditSHeader: 'Credits',
    noCreditsError: "You don't have any credits yet.",
    notifications: 'Notifications',
  },
  tr: {
    notifications: 'Bildirimler',
    noCreditsError: 'Henüz krediniz yok.',
    creditSHeader: 'Kontor',
    noBookingError: 'Henüz rezervasyon yapmadınız!',
    bookNow: 'REZERV',
    subHeaderDeals: 'Bugüne özel teklif',
    viewAll: 'Görüş',
    subHeaderPopular: 'En çok görüntülenen hizmetlerimiz',
    headerTodaysDeal: 'Bugünün İndirimi',
    headerPopular: 'Popüler',
    headerFavorites: 'Favoriler',
    tabProfile: 'Profil',
    tabBookings: 'Rezervasyon',
    tabDeals: 'İndirim',
    tabServices: 'Hizmet',
    tabExplore: 'Bulmak',
    slideOneHeader: 'şık saç',
    slideOneDesc: 've modern saç stillerini keşfedin.',
    slideTwoHeader: 'En iyi fırsatlar',
    slideTwoDesc:
      'Farklı mağazalarımızda en iyi saç fırsatlarını deneyimleyin.',
    slideThreeHeader: 'Hızlı rezervasyon',
    slideThreeDesc:
      'Yeni ve verimli uygulamamız ile online olarak hızlı rezervasyon yapabilirsiniz.',
    firstName: 'adı',
    lastName: 'Soyadı',
    confirmPassword: 'Şifreyi Onayla',
    login: 'Giriş yapmak',
    phone: 'telefon',
    password: 'parola',
    signup: 'Üye olmak',
    createAccount: 'Hesap oluşturmak',
    forgotPassword: 'Parolanızı mı unuttunuz',
    rememberMe: 'Beni hatırla',
    editProfile: 'Profilinizi düzenleyin',
    credits: 'Krediler ve Kuponlar',
    changeLanguage: 'Change Language',
    settings: 'Ayarlar',
    logOut: 'Çıkış yap',
    inviteFriends: 'Arkadaşları davet etmek',
    administrator: 'Yönetici',
    alreadyAccount: 'Zaten hesabınız var mı?',
    welcomeScreenText: 'Güzel ve özel stiller.',
    getStarted: 'Başlamak',
  },
  ru: {
    firstName: 'имя',
    lastName: 'фамилия',
    confirmPassword: 'Подтвердите пароль',
    login: 'Авторизоваться',
    phone: 'Телефон',
    password: 'пароль',
    signup: 'Подписаться',
    createAccount: 'Создать аккаунт',
    forgotPassword: 'Забыл пароль',
    rememberMe: 'Запомнить меня',
  },
});

export default strings;
